services:
  neo4j:
    image: neo4j:5.26.0
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_pagecache_size=512m
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - dokploy-network

  graphiti-mcp:
    image: zepai/knowledge-graph-mcp:latest
    build:
      context: .
      dockerfile: Dockerfile-new
    env_file:
      - .env
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "3000" # Expose the MCP server via HTTP for SSE transport
      - "8000"
    command:
      [
        "uv",
        "run",
        "graphiti_mcp_server_new.py",
        "--use-custom-entities",
        "--transport",
        "streamable-http",
      ]
    networks:
      - dokploy-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  dokploy-network:
    external: true
