services:
  neo4j:
    image: neo4j:5.26.0
    ports:
      - "7474" # HTTP
      - "7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    user: "7474:7474"
    env_file:
      - .env
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - dokploy-network

  graphiti-mcp:
    image: zepai/knowledge-graph-mcp:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8000" # Expose the MCP server via HTTP for SSE transport
    command: ["uv", "run", "graphiti_mcp_server.py", "--transport", "sse"]
    networks:
      - dokploy-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  dokploy-network:
    external: true
